name: agrilq
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets\images\f.png
    - assets\images\fo.png
    - assets\images\s.png
    - assets\images\t.png
    - assets\images\logo.png



